#!/usr/bin/env python
# encoding: utf-8

top = '.'
out = 'tmp'

version = '2.8'
unpacked = 'hello-%s' % version
tarball = '%s.tar.gz' % unpacked
url = 'http://ftp.gnu.org/gnu/hello/%s' % tarball
urlfile = '%s.url' % unpacked

def configure(cfg):
    return
    
def build(bld):
    urlnode = bld.path.find_or_declare(urlfile)
    print urlnode.abspath()
    bld(name = 'hello_seturl',
        rule = "echo %s > ${TGT}"%url, 
        target = urlfile, update_outputs = True)

    bld(name = 'hello_download',
        rule = "wget --quiet -nv --no-check-certificate -i ${SRC} -O ${TGT}",
        source = urlfile, target = tarball)

    bld(name = 'hello_unpack', 
        rule = "tar -xzf ${SRC} -C ${TGT[0].parent.parent}",
        source = tarball, target = '%s/configure' % unpacked)
    



