#+title: Building the =art= software framework and externals

This directory contains configuration files for building the  [[https://cdcvs.fnal.gov/redmine/projects/art][art] software framework and externals.

* Getting started.

The main configuration file is [[./main.cfg]] and some number of additional files are provided depending on make up of the suite.  Some files provide competing versions of groups or packages.

* Compiler

The framework requires a relatively new C++ compiler (gcc 4.7.1 at time of writing).  For systems that already provide a sufficient compiler, building one from source is optional.  The [[./buildtools.cfg]] file contains instructions to build it from source and [[./buildtools-nativegcc.cfg]] for using the system compiler.  

Build the compiler:
#+BEGIN_EXAMPLE
$ waf --prefix=/data3/bv/w/tmp/art-source-gcc \
  --orch-config=examples/art/main.cfg,examples/art/builttools.cfg \
  configure
#+END_EXAMPLE

Rely on the native compiler
#+BEGIN_EXAMPLE
$ waf --prefix=/data3/bv/w/tmp/art-native-gcc \
  --orch-config=examples/art/main.cfg,examples/art/builttools-nativegcc.cfg \
  configure
#+END_EXAMPLE

** FIXME: need to make specifying the list of =.cfg= files more friendly.  Maybe add a path/include mechanism.

